import ExperienceSection from '@/components/sections/Experience';
import HomeSection from '@/components/sections/Home';
import ProfileCard from '@/components/sections/Profile';
import ProjectsSection from '@/components/sections/Projects';
import SkillsSection from '@/components/sections/Skills';
import StudiesSection from '@/components/sections/Studies';
import { FaDatabase, FaHtml5, FaJava, FaPython, FaReact } from 'react-icons/fa';
import { FaBookOpen, FaCode, FaDev, FaHouse, FaImagePortrait, FaLaptopCode } from 'react-icons/fa6';
import {
  SiAmazonwebservices,
  SiApachekafka,
  SiDocker,
  SiFastapi,
  SiFlutter,
  SiHibernate,
  SiJavascript,
  SiJquery,
  SiKubernetes,
  SiMariadb,
  SiNetflix,
  SiNextdotjs,
  SiNodedotjs,
  SiOracle,
  SiPrisma,
  SiRadixui,
  SiReact,
  SiSpring,
  SiSpringboot,
  SiSpringsecurity,
  SiSupabase,
  SiTailwindcss,
  SiTensorflow,
  SiThymeleaf,
  SiTypescript,
  SiVercel,
} from 'react-icons/si';

export const siteConfig = {
  title: 'Resume',
  description: 'Diego Montes Novio - Developer',
  author: 'Diego Montes Novio',
  email: 'diego.montes@outlook.com',
  url: 'https://dmndev-resume.vercel.app',
  keywords: 'Diego Montes Novio, Diego Montes, Diego, Montes, Novio, dmndev, dmndev resume, devmon, devmon resume, developer, CV, Backend Developer, Full Stack Developer, Java Developer, Spring Developer, Hibernate Developer, JavaScript Developer, React Developer, Next.js Developer, Node.js Developer, Python Developer, Swift Developer, WatchOS Developer, iOS Developer, Android Developer, Flutter Developer, Mobile Developer, Web Developer, Frontend Developer, Backend Developer, Software Developer, Software Engineer, Analyst Developer, GasoAhorro',
  links: {
    github: 'https://github.com/makucg',
    linkedin: 'https://www.linkedin.com/in/diego-montes-novio-50503448/',
    sponsor: 'https://buymeacoffee.com/dmndev',
  },
  sections: {
    home: {
      id: 'home',
      title: 'Home',
      subtitle: 'Full Stack Developer',
      icon: FaHouse,
      section: HomeSection,
    },
    profile: {
      id: 'profile',
      title: 'Profile',
      subtitle: 'About me',
      icon: FaImagePortrait,
      section: ProfileCard,
    },
    experience: {
      id: 'experience',
      title: 'Experience',
      subtitle: 'My work experience',
      icon: FaLaptopCode,
      section: ExperienceSection,
    },
    studies: {
      id: 'studies',
      title: 'Studies',
      subtitle: 'My studies',
      icon: FaBookOpen,
      section: StudiesSection,
    },
    skills: {
      id: 'skills',
      title: 'Skills',
      subtitle: 'My skills',
      icon: FaCode,
      section: SkillsSection,
    },
    projects: {
      id: 'projects',
      title: 'Projects',
      subtitle: 'My projects',
      icon: FaDev,
      section: ProjectsSection,
    },
  },
  experiences: [
    {
      position: 'Analyst Developer',
      company: 'Indra',
      period: '2022 - Present',
      description: 'Project management for external vendors at Inditex:',
      details: [
        'Technical analysis, bug fixes, and code validation.',
        'Integration with other teams.',
      ],
      duration: '2 years',
      technologies: [
        { name: 'Java', icon: FaJava },
        { name: 'Spring', icon: SiSpring },
        { name: 'Hibernate', icon: SiHibernate },
        { name: 'SOAP', icon: null },
        { name: 'JavaScript', icon: SiJavascript },
        { name: 'DB2', icon: FaDatabase },
      ],
    },
    {
      position: 'Developer',
      company: 'Cuatroochenta',
      period: '2022',
      description: 'Microservices using Java 11 and Spring Boot:',
      details: [
        'RESTful APIs and architectural design contributions.',
      ],
      duration: '11 months',
      technologies: [
        { name: 'JavaScript', icon: SiJavascript },
        { name: 'JQuery', icon: SiJquery },
        { name: 'Thymeleaf', icon: SiThymeleaf },
      ],
    },
    {
      position: 'Analyst Developer',
      company: 'Indra',
      period: '2018 - Feb 2022',
      description: 'Project management for external vendors at Inditex:',
      details: [
        'Technical analysis, bug fixes, and code validation.',
        'Integration with other teams.',
        'Training of new team members.',
      ],
      duration: '4 years',
      technologies: [
        { name: 'Java', icon: FaJava },
        { name: 'Spring', icon: SiSpring },
        { name: 'Hibernate', icon: SiHibernate },
        { name: 'SOAP', icon: null },
        { name: 'JavaScript', icon: SiJavascript },
        { name: 'DB2', icon: FaDatabase },
      ],
    },
    {
      position: 'Developer',
      company: 'Coremain',
      period: '2009 - 2015',
      description: 'Development of Puntal project for government management:',
      details: [
        'Technical analysis, bug fixes, and code validation.',
        'Integration with other teams.',
        'Training of new team members.',
        'Training of clients.',
        'Deployment of new versions.',
      ],
      duration: '6 years',
      technologies: [
        { name: 'Java', icon: FaJava },
        { name: 'Hibernate', icon: SiHibernate },
        { name: 'Spring', icon: SiSpring },
        { name: 'Oracle', icon: SiOracle },
        { name: 'JasperReports', icon: null },
      ],
    },
  ],
  education: [
    {
      degree: 'Higher Technician Computer Systems Administration',
      institution: 'IES Xulián Magariños',
      period: '2007 - 2009',
      description: 'Focused on software development, data structures, network administration, system security, and server management.',
    },
    {
      degree: '1Z0-851 Java Standard Edition 6 Programmer Certified',
      institution: 'Oracle',
      period: '2010',
      description: 'Demonstrated proficiency in Java SE 6, including object-oriented programming, exception handling, and core APIs.',
    },
  ],
  projects: [
    {
      name: 'GasoAhorro',
      description: 'A dynamic web application designed to help users calculate and visualize their fuel cost savings when using a fuel card. Built with Next.js for a seamless user experience, Tailwind CSS for responsive and modern design, and TypeScript to ensure a robust and maintainable codebase. Hosted on Vercel for optimal performance and scalability.',
      technologies: [
        { name: 'Next.js', icon: SiNextdotjs },
        { name: 'Tailwind CSS', icon: SiTailwindcss },
        { name: 'TypeScript', icon: SiTypescript },
      ],
      url: 'https://gasoahorro-v4.vercel.app/',
      status: 'In development',
    },
    {
      name: 'Resume',
      description: 'A sleek and interactive personal resume showcasing my skills, projects, and experience. Developed using Next.js for efficient server-side rendering, styled with Tailwind CSS for a clean and professional look, and powered by TypeScript for reliability and scalability. Deployed on Vercel to ensure fast and consistent performance.',
      technologies: [
        { name: 'Next.js', icon: SiNextdotjs },
        { name: 'Tailwind CSS', icon: SiTailwindcss },
        { name: 'TypeScript', icon: SiTypescript },
        { name: 'RadixUI', icon: SiRadixui },
      ],
      url: 'https://dmndev-resume.vercel.app/',
      status: 'In development',
    },
    {
      name: 'PriceScout',
      description: 'Multi-Marketplace Price Comparison Platform: Real-Time Product Pricing Intelligence with Automated Web Scraping',
      technologies: [
        { name: 'Python', icon: FaPython },
        { name: 'FastAPI', icon: SiFastapi },
        { name: 'Next.js', icon: SiNextdotjs },
        { name: 'TypeScript', icon: SiTypescript },
        { name: 'Tailwind CSS', icon: SiTailwindcss },
        { name: 'RadixUI', icon: SiRadixui },
      ],
      status: 'In development, not deployed yet',
    },
    {
      name: 'Microservices',
      description: 'Developing a modern, secure, and scalable microservices infrastructure using Spring Boot. The system integrates Spring Security for authentication and authorization, Netflix OSS for service discovery and resilience, and Kubernetes with Docker for container orchestration. Kafka powers event-driven communication, Resilience4j ensures fault tolerance, and MariaDB is used as the primary database. Deployed with AWS, this architecture is designed for high availability, scalability, and reliability, following best practices in distributed systems.',
      technologies: [
        { name: 'Java', icon: FaJava },
        { name: 'Spring Boot', icon: SiSpringboot },
        { name: 'Spring Security', icon: SiSpringsecurity },
        { name: 'Spring Cloud', icon: null },
        { name: 'Netflix OSS', icon: SiNetflix },
        { name: 'Kubernetes', icon: SiKubernetes },
        { name: 'Docker', icon: SiDocker },
        { name: 'Kafka', icon: SiApachekafka },
        { name: 'Resilience4j', icon: null },
        { name: 'MariaDB', icon: SiMariadb },
        { name: 'AWS', icon: SiAmazonwebservices },
      ],
      status: 'In development, not deployed yet',
    },
    {
      name: 'Expense Analyzer',
      description: 'Financial Analytics Python Application: Expense Tracking with Intelligent Visualization.',
      technologies: [
        { name: 'Python', icon: FaPython },
        { name: 'TensorFlow', icon: SiTensorflow },
        { name: 'React', icon: FaReact },
        { name: 'FastAPI', icon: SiFastapi },
      ],
      status: 'Not started yet',
    },
    {
      name: 'TechRadar',
      description: 'Comprehensive Tech Stack Discovery Platform: Interactive Technology Search and Categorization Engine',
      technologies: [
        { name: 'Next.js', icon: SiNextdotjs },
        { name: 'TypeScript', icon: SiTypescript },
        { name: 'Tailwind CSS', icon: SiTailwindcss },
        { name: 'RadixUI', icon: SiRadixui },
        { name: 'Supabase', icon: SiSupabase },
        { name: 'Vercel', icon: SiVercel },
        { name: 'Prisma', icon: SiPrisma },
      ],
      status: 'Prototype Phase',
    },
  ],
  skills: [
    { name: 'Java', icon: FaJava, level: 90 },
    { name: 'SQL', icon: FaDatabase, level: 85 },
    { name: 'Spring Boot', icon: SiSpringboot, level: 70 },
    { name: 'Spring Security', icon: SiSpringsecurity, level: 60 },
    { name: 'Spring MVC', icon: SiSpring, level: 80 },
    { name: 'Spring Data JPA', icon: SiHibernate, level: 65 },
    { name: 'JavaScript', icon: SiJavascript, level: 70 },
    { name: 'TypeScript', icon: SiTypescript, level: 60 },
    { name: 'HTML/CSS', icon: FaHtml5, level: 60 },
    { name: 'Docker', icon: SiDocker, level: 50 },
    { name: 'React', icon: SiReact, level: 40 },
    { name: 'Node.js', icon: SiNodedotjs, level: 35 },
    { name: 'Python', icon: FaPython, level: 30 },
    { name: 'Flutter', icon: SiFlutter, level: 20 },
  ],
};
