#!/bin/sh
# Disable concurrent to run `check-types` after ESLint in lint-staged
# Add temporary `|| true` to avoid failing the pre-commit hook
cd "$(dirname "$0")/.." && npx --no lint-staged --concurrent false || true
